#logging:
#  level:
#    root: INFO
#  file:
#    name: nikron
#    path: /
#  logback:
#    rollingpolicy:
#      max-history: 5
#      max-file-size: 10MB
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
app:
  image:
    bucket: C:\Users\nmoiseev\IdeaProjects\spring-starter-nikron\images